name: Deploy to GCP
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
    - run: pnpm install
    - run: pnpm run build

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: infra
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v3
      with:
        project_id: renntg
        service_account: renntg-service-account@renntg.iam.gserviceaccount.com
        workload_identity_provider: projects/9489959707/locations/global/workloadIdentityPools/renntg-github/providers/renntg-github-provider
    - uses: hashicorp/setup-terraform@v4 
    - run: terraform init
    - run: terraform apply -auto-approve
    - uses: google-github-actions/upload-cloud-storage@v3
      with:
        path: dist
        destination: renntg.com
